# Fajr Adhan
################################################################################
- alias: Fujr Adhan
  id: '1517693010922'
  trigger:
    - platform: template
#     value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d")) == as_timestamp(strptime(states("sensor.islamic_prayer_time_isha"), "%Y-%m-%dT%H:%M:%S")) -3600 }}' # Activate this in November right after the time change
#     value_template: '{{ as_timestamp(strptime(states("sensor.time_date"), "%H:%M, %Y-%m-%d")) == as_timestamp(strptime(states("sensor.islamic_prayer_time_isha"), "%Y-%m-%dT%H:%M:%S")) +3600 }}' # Activate this in March right after the time change
      value_template: '{% set x = states(''sensor.fajr_prayer_time'') %} {{ now() >= today_at(strptime(x, "%I:%M %p").time()) }}'

  action:
    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.master_bedroom_speaker
            - media_player.main_floor_speaker
        volume_level: '0.50'

    # Fujr Adhan
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.master_bedroom_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_fajr_makkah.mp3
        media_content_type: audio/mp3
    - delay: '00:03:59'

    # Adhan Dua
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.master_bedroom_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/dua/dua-e-adhan.mp3
        media_content_type: audio/mp3
    - delay: '00:00:19'

    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.master_bedroom_speaker
            - media_player.main_floor_speaker
        volume_level: '0.40'

    #- service: media_player.volume_set
    #  data:
    #    entity_id:
    #        - media_player.family_room_speaker
    #        - media_player.guest_room_wifi
    #    volume_level: '0.29'

    # 96 Surah Al'Alaq
    #- service: media_extractor.play_media
    #  data:
    #    entity_id:
    #        - media_player.family_room_speaker
    #        - media_player.guest_room_wifi
    #    media_content_id: http://copernicium.universe.hm/aud/surah/quran_96.mp3
    #    media_content_type: audio/mp3

    #- delay: '00:02:46'

    # 109 Surah Al'Kafirun
    #- service: media_extractor.play_media
    #  data:
    #    entity_id:
    #        - media_player.family_room_speaker
    #        - media_player.guest_room_wifi
    #    media_content_id: http://copernicium.universe.hm/aud/surah/quran_109.mp3
    #    media_content_type: audio/mp3

    #- delay: '00:01:19'

    # 110 Surah An'Nasr
    #- service: media_extractor.play_media
    #  data:
    #    entity_id:
    #        - media_player.family_room_speaker
    #        - media_player.guest_room_wifi
    #    media_content_id: http://copernicium.universe.hm/aud/surah/quran_110.mp3
    #    media_content_type: audio/mp3

    #- delay: '00:00:57'

    # 01 Surah Al'Fatiha
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.master_bedroom_speaker
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_01.mp3
        media_content_type: audio/mp3
    - delay: '00:01:28'

    # 112 Surah Al'Ikhlas
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.master_bedroom_speaker
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_112.mp3
        media_content_type: audio/mp3
    - delay: '00:00:41'

    # 113 Surah Al'Falaq
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.master_bedroom_speaker
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_113.mp3
        media_content_type: audio/mp3
    - delay: '00:00:56'

    # 114 Surah An'Nas
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.master_bedroom_speaker
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_114.mp3
        media_content_type: audio/mp3
    - delay: '00:01:17'

    # Ayat'ul Kursi
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.master_bedroom_speaker
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/ayah/ayat_ul-kursi.mp3
        media_content_type: audio/mp3


# Dhuhr Adhan
################################################################################
- alias: Dhuhr Adhan
  id: '1517693010923'
  trigger:
    - platform: template
      value_template: '{% set x = states(''sensor.dhuhr_prayer_time'') %} {{ now() >= today_at(strptime(x, "%I:%M %p").time()) }}'

  action:
    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        volume_level: '0.5'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_al-aqsa.mp3 
#       media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_makkah.mp3
        media_content_type: audio/mp3
    #- delay: '00:03:22'
    - delay: '00:04:15'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/dua/dua-e-adhan.mp3
        media_content_type: audio/mp3
    - delay: '00:00:19'

    # 01 Surah Al'Fatiha
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_01.mp3
        media_content_type: audio/mp3
    - delay: '00:01:28'

    # 112 Surah Al'Ikhlas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_112.mp3
        media_content_type: audio/mp3
    - delay: '00:00:41'

    # 113 Surah Al'Falaq
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_113.mp3
        media_content_type: audio/mp3

    - delay: '00:00:56'

    # 114 Surah An'Nas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_114.mp3
        media_content_type: audio/mp3
    - delay: '00:01:17'

    # Ayat'ul Kursi
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/ayah/ayat_ul-kursi.mp3
        media_content_type: audio/mp3

# Asr Adhan
################################################################################
- alias: Asr Adhan
  id: '1517693010924'
  trigger:
    - platform: template
      value_template: '{% set x = states(''sensor.asr_prayer_time'') %} {{ now() >= today_at(strptime(x, "%I:%M %p").time()) }}'

  action:
    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        volume_level: '0.5'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
#       media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_makkah.mp3
        media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_al-aqsa.mp3
        media_content_type: audio/mp3
#   - delay: '00:03:22'
    - delay: '00:04:15'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/dua/dua-e-adhan.mp3
        media_content_type: audio/mp3
    - delay: '00:00:19'

    # 01 Surah Al'Fatiha
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_01.mp3
        media_content_type: audio/mp3
    - delay: '00:01:28'

    # 112 Surah Al'Ikhlas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_112.mp3
        media_content_type: audio/mp3
    - delay: '00:00:41'

    # 113 Surah Al'Falaq
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_113.mp3
        media_content_type: audio/mp3
    - delay: '00:00:56'

    # 114 Surah An'Nas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_114.mp3
        media_content_type: audio/mp3
    - delay: '00:01:17'

    # Ayat'ul Kursi
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/ayah/ayat_ul-kursi.mp3
        media_content_type: audio/mp3

# Mughrib Adhan
################################################################################
- alias: Maghrib Adhan
  id: '1517693010925'
  trigger:
    - platform: template
      value_template: '{% set x = states(''sensor.mughrib_prayer_time'') %} {{ now() >= today_at(strptime(x, "%I:%M %p").time()) }}'
      
  action:
    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        volume_level: '1.0'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_al-maghrib_madinah.mp3
#       media_content_id: http://copernicium.universe.hm/aud/adhan/bahrain_tv_athan_akmagraib.mp3
        media_content_type: audio/mp3
    - delay: '00:03:37' # adhan_al-mughrib_madinah

    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        volume_level: '0.5'

    - service: media_extractor.play_media
      data:
        entity_id: 
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/dua/dua-e-adhan.mp3
        media_content_type: audio/mp3
    - delay: '00:00:19'

    # 01 Surah Al'Fatiha
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_01.mp3
        media_content_type: audio/mp3
    - delay: '00:01:28'

    # 112 Surah Al'Ikhlas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_112.mp3
        media_content_type: audio/mp3
    - delay: '00:00:41'

    # 113 Surah Al'Falaq
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_113.mp3
        media_content_type: audio/mp3
    - delay: '00:00:56'

    # 114 Surah An'Nas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_114.mp3
        media_content_type: audio/mp3

    - delay: '00:01:17'

    # Ayat'ul Kursi
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/ayah/ayat_ul-kursi.mp3
        media_content_type: audio/mp3

# Isha Adhan
################################################################################
- alias: Isha Adhan
  id: '1517693010926'
  trigger:
    - platform: template
      value_template: '{% set x = states(''sensor.isha_prayer_time'') %} {{ now() >= today_at(strptime(x, "%I:%M %p").time()) }}'

  action:
    - service: media_player.volume_set
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        volume_level: '0.5'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
#       media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_makkah.mp3
        media_content_id: http://copernicium.universe.hm/aud/adhan/adhan_al-aqsa.mp3
        media_content_type: audio/mp3
    #- delay: '00:03:22'
    - delay: '00:04:15'

    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.master_bedroom_speaker
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/dua/dua-e-adhan.mp3
        media_content_type: audio/mp3
    - delay: '00:00:19'

    # 01 Surah Al'Fatiha
    - service: media_extractor.play_media
      data:
        entity_id:
          - media_player.family_room_speaker
          - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_01.mp3
        media_content_type: audio/mp3
    - delay: '00:01:28'

    # 112 Surah Al'Ikhlas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_112.mp3
        media_content_type: audio/mp3
    - delay: '00:00:41'

    # 113 Surah Al'Falaq
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_113.mp3
        media_content_type: audio/mp3
    - delay: '00:00:56'

    # 114 Surah An'Nas
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/surah/quran_114.mp3
        media_content_type: audio/mp3
    - delay: '00:01:17'

    # Ayat'ul Kursi
    - service: media_extractor.play_media
      data:
        entity_id:
            - media_player.family_room_speaker
            - media_player.main_floor_speaker
        media_content_id: http://copernicium.universe.hm/aud/ayah/ayat_ul-kursi.mp3
        media_content_type: audio/mp3